language: python
python:
  - 3.7.6
before_install:
  - python3 --version
  - pip3 install -U pip
  - pip3 install -U pytest
  - pip3 install -U pytest-cov
  - pip3 install -U codecov
install:
  - pip3 install .
script: python3 -m pytest
after_success:
  - python 3 -m codecov
